Modules/ComplaintAndSuggestion/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\ComplaintAndSuggestion\Http\Controllers\ComplaintController;
use Modules\ComplaintAndSuggestion\Http\Controllers\SuggestionController;

Route::middleware('auth')->group(function () {
    Route::middleware('admin')->group(function () {
        Route::get('/complaints-list', [ComplaintController::class, 'getAllComplaints'])
            ->name('showAllComplaints');
        Route::resource('complaints', 'ComplaintController');

        Route::get('/suggestions-list', [SuggestionController::class, 'getAllSuggestions'])
            ->name('showAllSuggestions');
        Route::resource('suggestions', 'SuggestionController');
    });

    Route::get('/my-complaints', [ComplaintController::class, 'getUserComplaints'])
        ->name('showComplaintsForUser');
    Route::get('/complaints/create', [ComplaintController::class, 'create'])
        ->name('complaints.create');
    Route::post('/complaints', [ComplaintController::class, 'store'])
        ->name('complaints.store');

    Route::get('/my-suggestions', [SuggestionController::class, 'getUserSuggestions'])
        ->name('showSuggestionsForUser');
    Route::get('/suggestions/create', [SuggestionController::class, 'create'])
        ->name('suggestions.create');
    Route::post('/suggestions', [SuggestionController::class, 'store'])
        ->name('suggestions.store');
});

Route::middleware('guest')->group(function () {
    Route::get('/complaints', [ComplaintController::class, 'getVisibleComplaints'])
        ->name('showComplaintsForGuest');

    Route::get('/suggestions', [SuggestionController::class, 'getVisibleSuggestions'])
        ->name('showSuggestionsForGuest');
});

Route::get('/suggestions/{suggestion} ', [SuggestionController::class, 'show'])
    ->name('suggestions.show');

Route::get('/complaints/{complaint} ', [ComplaintController::class, 'show'])
    ->name('complaints.show');

Modules/ComplaintAndSuggestion/Resources/views/layouts/complaint-card.blade.php
<div class="card">
    <div class="main-link"> Имя пользователя: {{$complaint->user->name}}</div>
    <div class="main-link"> Дата создания: {{$complaint->created_at}}</div>
    <div class="main-link"> Жалоба: {{$complaint->text}}</div>
    <div class="main-link"> Статус: {{$complaint->status->name}}</div>
    <img width="300" height="300" src="{{$complaint->image}}">
    @if(isset(Auth::user()->id) && Auth::user()->isAdmin())
        <button><a class="main-link" href="{{ route('complaints.edit', $complaint) }}">Редактировать жалобу</a></button>

        <form action="{{ route('complaints.destroy', $complaint) }}" method="POST">
            @csrf
            @method('DELETE')
            <input type="submit" value="Удалить">
        </form>
    @endif

</div>

Modules/ComplaintAndSuggestion/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ЖП: @yield('title')</title>

    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a class="main-link" href="{{ route('home') }}">Главная</a></li>
                    @guest
                        <li> <a class="main-link" href="{{ route('showComplaintsForGuest') }}">Все жалобы</a></li>
                        <li> <a class="main-link" href="{{ route('showSuggestionsForGuest') }}">Все предложения</a></li>
                    @else
                        @if(Auth::user()->isAdmin())
                            <li> <a class="main-link" href="{{ route('showAllComplaints') }}">Жалобы</a></li>
                            <li> <a class="main-link" href="{{ route('showAllSuggestions') }}">Предложения</a></li>
                        @else
                            <li> <a class="main-link" href="{{ route('showComplaintsForUser') }}">Мои жалобы</a></li>
                            <li> <a class="main-link" href="{{ route('showSuggestionsForUser') }}">Мои предложения</a></li>
                        @endif
                    @endguest
                </ul>

                @guest
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="main-link" href="{{ route('login') }}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="main-link" href="{{ route('register') }}">Зарегистрироваться</a>
                        </li>
                    </ul>
                @endguest

                @auth
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item dropdown">
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="main-link" href="{{ route('logout')}}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Выйти
                                </a>

                                <form id="logout-form" action="{{ route('logout')}}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                @endauth
            </div>
        </div>
    </nav>

    <div class="py-4">
        <div class="container">
            <div class="row justify-content-center">
                @yield('content')
            </div>
        </div>
    </div>
</div>
</body>
</html>

Modules/ComplaintAndSuggestion/Resources/views/layouts/suggestion-card.blade.php
<div class="card">
    <div class="main-link"> Имя пользователя: {{$suggestion->user->name}}</div>
    <div class="main-link"> Дата создания: {{$suggestion->created_at}}</div>
    <div class="main-link"> Жалоба: {{$suggestion->text}}</div>
    <div class="main-link"> Статус: {{$suggestion->status->name}}</div>
    @if(isset(Auth::user()->id) && Auth::user()->isAdmin())
        <button><a class="main-link" href="{{ route('suggestions.edit', $suggestion) }}">Редактировать жалобу</a></button>

        <form action="{{ route('suggestions.destroy', $suggestion) }}" method="POST">
            @csrf
            @method('DELETE')
            <input type="submit" value="Удалить">
        </form>
    @endif
</div>