Modules/ComplaintAndSuggestion/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\ComplaintAndSuggestion\Http\Controllers\ComplaintController;
use Modules\ComplaintAndSuggestion\Http\Controllers\SuggestionController;

Route::middleware('auth')->group(function () {
    Route::middleware('admin')->group(function () {
        Route::get('/complaints-list', [ComplaintController::class, 'getAllComplaints'])
            ->name('showAllComplaints');
        Route::resource('complaints', 'ComplaintController');

        Route::get('/suggestions-list', [SuggestionController::class, 'getAllSuggestions'])
            ->name('showAllSuggestions');
        Route::resource('suggestions', 'SuggestionController');
    });

    Route::get('/my-complaints', [ComplaintController::class, 'getUserComplaints'])
        ->name('showComplaintsForUser');
    Route::get('/complaints/create', [ComplaintController::class, 'create'])
        ->name('complaints.create');
    Route::post('/complaints', [ComplaintController::class, 'store'])
        ->name('complaints.store');

    Route::get('/my-suggestions', [SuggestionController::class, 'getUserSuggestions'])
        ->name('showSuggestionsForUser');
    Route::get('/suggestions/create', [SuggestionController::class, 'create'])
        ->name('suggestions.create');
    Route::post('/suggestions', [SuggestionController::class, 'store'])
        ->name('suggestions.store');
});

Route::middleware('guest')->group(function () {
    Route::get('/complaints', [ComplaintController::class, 'getVisibleComplaints'])
        ->name('showComplaintsForGuest');

    Route::get('/suggestions', [SuggestionController::class, 'getVisibleSuggestions'])
        ->name('showSuggestionsForGuest');
});

Route::get('/suggestions/{suggestion} ', [SuggestionController::class, 'show'])
    ->name('suggestions.show');

Route::get('/complaints/{complaint} ', [ComplaintController::class, 'show'])
    ->name('complaints.show');

Modules/ComplaintAndSuggestion/Entities/Suggestion.php
<?php

namespace Modules\ComplaintAndSuggestion\Entities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Modules\ComplaintAndSuggestion\Database\factories\SuggestionFactory;
use Modules\User\Entities\User;
use Carbon\Carbon;

/**
 * @property integer         $id
 * @property string          $text
 * @property integer         $status_id
 * @property integer         $user_id
 * @property boolean         $is_visible
 * @property Carbon|null     $created_at
 * @property Carbon|null     $updated_at
 *
 * @property-read User       $user
 * @property-read Status     $status
 *
 * @static SuggestionFactory newFactory
 *
 * @extends Model
 */
class Suggestion extends Model
{
    use HasFactory;

    public const FIELD_ID = 'id';
    public const FIELD_TEXT = 'text';
    public const FIELD_STATUS_ID = 'status_id';
    public const FIELD_USER_ID = 'user_id';
    public const FIELD_IS_VISIBLE = 'is_visible';
    public const TABLE_NAME = 'suggestions';
    public const NUMBER_CARD_PER_PAGE = 5;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $fillable = [
        self::FIELD_ID,
        self::FIELD_TEXT,
        self::FIELD_STATUS_ID,
        self::FIELD_IS_VISIBLE,
        self::FIELD_USER_ID,
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function status(): BelongsTo
    {
        return $this->belongsTo(Status::class);
    }

    protected static function newFactory()
    {
        return new SuggestionFactory();
    }
}

Modules/ComplaintAndSuggestion/Http/Controllers/SuggestionController.php
<?php

namespace Modules\ComplaintAndSuggestion\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\ComplaintAndSuggestion\Entities\Complaint;
use Modules\ComplaintAndSuggestion\Entities\Status;
use Modules\ComplaintAndSuggestion\Entities\Suggestion;
use Modules\ComplaintAndSuggestion\Http\Requests\SuggestionRequest;

class SuggestionController extends Controller
{
    public function getVisibleSuggestions()
    {
        $suggestions = Suggestion::query()
            ->where(Suggestion::FIELD_IS_VISIBLE, true)
            ->paginate(Suggestion::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::suggestions.index', compact('suggestions'));
    }

    public function getUserSuggestions()
    {
        $suggestions = (Auth::user())
            ->suggestions()
            ->paginate(Suggestion::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::suggestions.index', compact('suggestions'));
    }

    public function getAllSuggestions()
    {
        $suggestions = Suggestion::query()->paginate(Suggestion::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::suggestions.index', compact('suggestions'));
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('complaintandsuggestion::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('complaintandsuggestion::suggestions.form');
    }

    /**
     * Store a newly created resource in storage.
     * @param SuggestionRequest $request
     * @return Renderable
     */
    public function store(SuggestionRequest $request)
    {
        $params = $request->all();
        $params[Suggestion::FIELD_USER_ID] = Auth::id();
        Suggestion::create($params);

        return redirect()->route('home');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('complaintandsuggestion::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $suggestion = Suggestion::query()->findOrFail($id);
        $statuses = Status::all();
        return view(
            'complaintandsuggestion::suggestions.form',
            compact('suggestion', 'statuses')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param SuggestionRequest $request
     * @param Suggestion $suggestion
     * @return Renderable
     */
    public function update(SuggestionRequest $request, Suggestion $suggestion)
    {
        $params = $request->all();
        $params[Suggestion::FIELD_IS_VISIBLE] = $request->has(Suggestion::FIELD_IS_VISIBLE);
        $suggestion->update($params);

        return redirect()->route('showAllSuggestions');
    }

    /**
     * Remove the specified resource from storage.
     * @param Suggestion $suggestion
     * @return Renderable
     */
    public function destroy(Suggestion $suggestion)
    {
        $suggestion->delete();
        return \Redirect::route('showAllSuggestions');
    }
}

Modules/ComplaintAndSuggestion/Resources/views/suggestions/form.blade.php
@extends('complaintandsuggestion::layouts.master')

@isset($suggestion)
    @section('title', 'Редактировать предложение #' . $suggestion->id)
@else
    @section('title', 'Добавить предложение')
@endisset

@section('content')
    <div>
        @isset($suggestion)
            <h1>Редактировать предложение #{{ $suggestion->id }}</h1>
        @else
            <h1>Добавить предложение</h1>
        @endisset

        <form method="POST" enctype="multipart/form-data"
              @isset($suggestion)
                  action="{{ route('suggestions.update', $suggestion) }}"
              @else
                  action="{{ route('suggestions.store') }}"
            @endisset
        >
            <div>
                @isset($suggestion)
                    @method('PUT')
                @endisset
                @csrf
                <div>
                    <label for="code">Текст: </label>
                    <div>
                        @error('text')
                        <div>{{ $message }}</div>
                        @enderror
                        <input type="text" name="text" id="text"
                               value="{{ old('text', isset($suggestion) ? $suggestion->text : null) }}">
                    </div>
                </div>
                <br>
                    @if(Auth::user()->isAdmin() && isset($suggestion))
                        <br>
                        <div>
                            <br>
                            <div>
                                <label for="status_id" >Статус:  </label>
                                <div>
                                    <select name="status_id" id="status_id" class="form-control">
                                        @foreach($statuses as $status)
                                            <option value="{{ $status->id }}"
                                                    @isset($suggestion)
                                                        @if($suggestion->status_id == $status->id)
                                                            selected
                                                    @endif
                                                    @endisset
                                            >{{ $status->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <br>
                        </div>
                        <br>
                        <div>
                            <label for="code">Видимость для пользователей: </label>
                            <div>
                                @error('is_visible')
                                <div>{{ $message }}</div>
                                @enderror
                                <input type="checkbox" name="is_visible" id="is_visible" value="{{ $suggestion->is_visible}}"

                                       @if($suggestion->is_visible !== 0)
                                           checked="checked"
                                        @endif
                                >
                            </div>
                        </div>
                    @endif
                <button>Сохранить</button>
            </div>
        </form>
    </div>
@endsection

Modules/ComplaintAndSuggestion/Resources/views/suggestions/index.blade.php
@extends('complaintandsuggestion::layouts.master')

@section('title', 'Предложения')
@section('content')
    <button><a class="main-button" href="{{ route('suggestions.create') }}">Оставить предложение</a></button>
    <div>
        <div class="row">
            @foreach($suggestions as $suggestion)
                @include('complaintandsuggestion::layouts.suggestion-card', compact('suggestion'))
            @endforeach
        </div>
    </div>

    {{ $suggestions->links() }}
@endsection