Modules/ComplaintAndSuggestion/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\ComplaintAndSuggestion\Http\Controllers\ComplaintController;
use Modules\ComplaintAndSuggestion\Http\Controllers\SuggestionController;

Route::middleware('auth')->group(function () {
    Route::middleware('admin')->group(function () {
        Route::get('/complaints-list', [ComplaintController::class, 'getAllComplaints'])
            ->name('showAllComplaints');
        Route::resource('complaints', 'ComplaintController');

        Route::get('/suggestions-list', [SuggestionController::class, 'getAllSuggestions'])
            ->name('showAllSuggestions');
        Route::resource('suggestions', 'SuggestionController');
    });

    Route::get('/my-complaints', [ComplaintController::class, 'getUserComplaints'])
        ->name('showComplaintsForUser');
    Route::get('/complaints/create', [ComplaintController::class, 'create'])
        ->name('complaints.create');
    Route::post('/complaints', [ComplaintController::class, 'store'])
        ->name('complaints.store');

    Route::get('/my-suggestions', [SuggestionController::class, 'getUserSuggestions'])
        ->name('showSuggestionsForUser');
    Route::get('/suggestions/create', [SuggestionController::class, 'create'])
        ->name('suggestions.create');
    Route::post('/suggestions', [SuggestionController::class, 'store'])
        ->name('suggestions.store');
});

Route::middleware('guest')->group(function () {
    Route::get('/complaints', [ComplaintController::class, 'getVisibleComplaints'])
        ->name('showComplaintsForGuest');

    Route::get('/suggestions', [SuggestionController::class, 'getVisibleSuggestions'])
        ->name('showSuggestionsForGuest');
});

Route::get('/suggestions/{suggestion} ', [SuggestionController::class, 'show'])
    ->name('suggestions.show');

Route::get('/complaints/{complaint} ', [ComplaintController::class, 'show'])
    ->name('complaints.show');

Modules/ComplaintAndSuggestion/Entities/Complaint.php
<?php

namespace Modules\ComplaintAndSuggestion\Entities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Modules\ComplaintAndSuggestion\Database\factories\ComplaintFactory;
use Modules\User\Entities\User;
use Carbon\Carbon;

/**
 * @property integer        $id
 * @property string         $text
 * @property integer        $status_id
 * @property integer        $user_id
 * @property boolean        $is_visible
 * @property string         $image
 * @property Carbon|null    $created_at
 * @property Carbon|null    $updated_at
 *
 * @property-read User      $user
 * @property-read Status    $status
 *
 * @static ComplaintFactory newFactory
 *
 * @extends Model
 */
class Complaint extends Model
{
    use HasFactory;

    public const FIELD_ID = 'id';
    public const FIELD_TEXT = 'text';
    public const FIELD_STATUS_ID = 'status_id';
    public const FIELD_USER_ID = 'user_id';
    public const FIELD_IS_VISIBLE = 'is_visible';
    public const FIELD_IMAGE = 'image';
    public const TABLE_NAME = 'complaints';
    public const NUMBER_CARD_PER_PAGE = 5;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $fillable = [
        self::FIELD_ID,
        self::FIELD_TEXT,
        self::FIELD_STATUS_ID,
        self::FIELD_IS_VISIBLE,
        self::FIELD_USER_ID,
        self::FIELD_IMAGE
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function status(): BelongsTo
    {
        return $this->belongsTo(Status::class);
    }

    protected static function newFactory()
    {
        return new ComplaintFactory();
    }
}

Modules/ComplaintAndSuggestion/Http/Controllers/ComplaintController.php
<?php

namespace Modules\ComplaintAndSuggestion\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\ComplaintAndSuggestion\Entities\Complaint;
use Modules\ComplaintAndSuggestion\Entities\Status;
use Modules\ComplaintAndSuggestion\Http\Requests\ComplaintRequest;
use Storage;

class ComplaintController extends Controller
{
    public function getVisibleComplaints()
    {
        $complaints = Complaint::query()
            ->where(Complaint::FIELD_IS_VISIBLE, true)
            ->paginate(Complaint::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::complaints.index', compact('complaints'));
    }

    public function getUserComplaints()
    {
        $complaints = (Auth::user())
            ->complaints()
            ->paginate(Complaint::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::complaints.index', compact('complaints'));
    }

    public function getAllComplaints()
    {
        $complaints = Complaint::query()->paginate(Complaint::NUMBER_CARD_PER_PAGE);

        return view('complaintandsuggestion::complaints.index', compact('complaints'));
    }


    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('complaintandsuggestion::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('complaintandsuggestion::complaints.form');
    }

    /**
     * Store a newly created resource in storage.
     * @param ComplaintRequest $request
     * @return RedirectResponse
     */
    public function store(ComplaintRequest $request)
    {
        $params = $request->all();
        $params = $this->saveImage($params, $request);
        $params[Complaint::FIELD_USER_ID] = Auth::id();
        Complaint::create($params);

        return redirect()->route('home');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('complaintandsuggestion::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $complaint = Complaint::query()->findOrFail($id);
        $statuses = Status::all();
        return view(
            'complaintandsuggestion::complaints.form',
            compact('complaint', 'statuses')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param ComplaintRequest $request
     * @param Complaint $complaint
     * @return RedirectResponse
     */
    public function update(ComplaintRequest $request, Complaint $complaint)
    {
        $params = $request->all();
        $params[Complaint::FIELD_IS_VISIBLE] = $request->has(Complaint::FIELD_IS_VISIBLE);
        $params = $this->saveImage($params, $request, $complaint);
        $complaint->update($params);

        return redirect()->route('showAllComplaints');
    }

    /**
     * Remove the specified resource from storage.
     * @param Complaint $complaint
     * @return RedirectResponse
     */
    public function destroy(Complaint $complaint)
    {
        $complaint->delete();
        return \Redirect::route('showAllComplaints');
    }

    protected function saveImage($params, $request, $complaint = null)
    {
        unset($params[Complaint::FIELD_IMAGE]);
        if ($request->has(Complaint::FIELD_IMAGE)) {
            if (isset($complaint)) {
                Storage::delete($complaint->image);
            }

            $params[Complaint::FIELD_IMAGE] = $request->file(Complaint::FIELD_IMAGE)->store('complaints');
            $params[Complaint::FIELD_IMAGE] = Storage::url(DIRECTORY_SEPARATOR . $params[Complaint::FIELD_IMAGE]);
        }

        return $params;
    }
}

Modules/ComplaintAndSuggestion/Resources/views/complaints/form.blade.php
@extends('complaintandsuggestion::layouts.master')

@isset($complaint)
    @section('title', 'Редактировать жалобу #' . $complaint->id)
@else
    @section('title', 'Добавить жалобу')
@endisset

@section('content')
    <div>
        @isset($complaint)
            <h1>Редактировать жалобу #{{ $complaint->id }}</h1>
        @else
            <h1>Добавить жалобу</h1>
        @endisset

        <form method="POST" enctype="multipart/form-data"
              @isset($complaint)
                  action="{{ route('complaints.update', $complaint) }}"
              @else
                  action="{{ route('complaints.store') }}"
            @endisset
        >
            <div>
                @isset($complaint)
                    @method('PUT')
                @endisset
                @csrf
                <div>
                    <label for="code">Текст: </label>
                    <div>
                        @error('text')
                        <div>{{ __($message) }}</div>
                        @enderror
                        <input type="text" name="text" id="text"
                               value="{{ old('text', isset($complaint) ? $complaint->text : null) }}">
                    </div>
                </div>
                @if(Auth::user()->isAdmin() && isset($complaint))
                    <br>
                    <div>
                        <br>
                        <div>
                            <label for="status_id" >Статус: </label>
                            <div>
                                <select name="status_id" id="status_id" class="form-control">
                                    @foreach($statuses as $status)
                                        <option value="{{ $status->id }}"
                                                @isset($complaint)
                                                    @if($complaint->status_id == $status->id)
                                                        selected
                                                @endif
                                                @endisset
                                        >{{ $status->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                    </div>
                    <br>
                    <div>
                        <label for="code">Видимость для пользователей: </label>
                        <div>
                            @error('is_visible')
                            <div>{{ $message }}</div>
                            @enderror
                            <input type="checkbox" name="is_visible" id="is_visible" value="{{ $complaint->is_visible}}"

                                   @if($complaint->is_visible !== 0)
                                       checked="checked"
                                   @endif
                            >
                        </div>
                    </div>
                @endif
                <br>
                <div>
                    <label for="image">Картинка: </label>
                    @isset($complaint->image)
                        <img src="{{ $complaint->image }}">
                    @endisset
                    <div>
                        <label>
                            Загрузить <input type="file" style="display: none;" name="image" id="image">
                        </label>
                    </div>
                </div>
                <button>Сохранить</button>
            </div>
        </form>
    </div>
@endsection

Modules/ComplaintAndSuggestion/Resources/views/complaints/index.blade.php
@extends('complaintandsuggestion::layouts.master')

@section('title', 'Жалобы')
@section('content')
    <button><a class="main-button" href="{{ route('complaints.create') }}">Оставить жалобу</a></button>
    <div>
        <div class="row">
            @foreach($complaints as $complaint)
                @include('complaintandsuggestion::layouts.complaint-card', compact('complaint'))
            @endforeach
        </div>
    </div>

    {{ $complaints->links() }}
@endsection